### ISSUE TITLE
Configure Production Environment for GotHired.ai on Hostinger VPS using Kamal 2

### ISSUE THREAD

**Issue by gabrielrubens** [gabrielrubens/gothired#7]
## Overview
Set up our Rails 8 application (GotHired.ai) in production environment on Hostinger VPS using Kamal 2 for deployment. This issue covers the complete configuration process from provisioning the server to automating deployments.

## Objectives
- Set up Hostinger VPS for running our Rails 8 application
- Configure Kamal 2 for zero-downtime deployments
- Set up Docker registry access and caching
- Implement SSL certificates via Let's Encrypt
- Establish automated deployment pipeline

### 1. Hostinger VPS Setup
- [ ] Purchase a Hostinger VPS plan (minimum recommended: 2GB RAM, 1 vCPU)
- [ ] Set up DNS records for our domain (point `gothired.ai` and `www.gothired.ai` to the VPS IP)
- [ ] Configure SSH access:
  ```bash
  # Generate SSH key if you don't have one
  ssh-keygen -t ed25519 -C "deploy@gothired.ai"
  
  # Add public key to Hostinger VPS through their control panel
  ```
- [ ] Create a non-root user with sudo privileges on the VPS:
  ```bash
  adduser deploy
  usermod -aG sudo deploy
  ```
- [ ] Test SSH access to the server:
  ```bash
  ssh deploy@your-server-ip
  ```

### 2. GitHub Repository Configuration
- [ ] Add GitHub Actions workflow for Kamal deployments (.github/workflows/deploy.yml):
  ```yaml
  name: Deploy
  
  on:
    push:
      branches: [main]
      
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Deploy to production
          env:
            KAMAL_REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            KAMAL_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          run: |
            bundle install
            bundle exec kamal deploy
  ```
- [ ] Set up repository secrets in GitHub:
  - `SSH_PRIVATE_KEY`: Your deployment SSH private key
  - `DOCKER_USERNAME`: Docker Hub username
  - `DOCKER_PASSWORD`: Docker Hub access token
  - `RAILS_MASTER_KEY`: Your Rails master key

### 3. Kamal 2 Configuration
- [ ] Initialize Kamal in your project:
  ```bash
  bundle exec kamal init
  ```
- [ ] Update the generated `config/deploy.yml` file:
  ```yaml
  # Kamal deploy configuration
  service: gothired
  
  image: yourdockerhub/gothired
  
  servers:
    web:
      hosts:
        - deploy@your-server-ip
    sidekiq:
      cmd: bundle exec sidekiq
      hosts:
        - deploy@your-server-ip
  
  registry:
    # Docker Hub
    username:
      - KAMAL_REGISTRY_USERNAME
    password:
      - KAMAL_REGISTRY_PASSWORD
  
  builder:
    arch: amd64
    cache:
      type: gha
      options: mode=max
      image: app-build-cache
  
  env:
    clear:
      # Standard Rails environment variables
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      RAILS_SERVE_STATIC_FILES: true
      DB_HOST: gothired-db
    secret:
      - RAILS_MASTER_KEY
      - GEMINI_API_KEY
  
  # Database configuration as an accessory
  accessories:
    db:
      image: postgres:15
      host: deploy@your-server-ip
      env:
        clear:
          POSTGRES_USER: deploy
          POSTGRES_DB: gothired_production
        secret:
          - POSTGRES_PASSWORD
      volumes:
        - /var/lib/postgresql/data:/var/lib/postgresql/data
    redis:
      image: redis:7
      host: deploy@your-server-ip
      
  # Configure SSL and domain
  proxy:
    ssl: true
    host: gothired.ai
    # If using multiple hostnames:
    # hosts:
    #   - gothired.ai
    #   - www.gothired.ai
    # Set custom certificate names (optional)
    # custom_certificate_arn: arn:aws:acm:us-east-1:123456789012:certificate/abcdef01-2345-6789-abcd-ef0123456789
  ```

- [ ] Create local secrets for Kamal:
  ```bash
  mkdir -p .kamal/secrets
  echo "your-postgres-password" > .kamal/secrets/POSTGRES_PASSWORD
  echo "your-gemini-api-key" > .kamal/secrets/GEMINI_API_KEY
  ```
  (Remember to add `.kamal/secrets/` to your `.gitignore` file)

- [ ] Update your database.yml for production:
  ```yaml
  production:
    
    host: 
  ```

### 4. Deployment Process
- [ ] Setup the server with Kamal:
  ```bash
  bundle exec kamal setup
  ```

- [ ] Start the database accessory:
  ```bash
  bundle exec kamal accessory boot db
  ```

- [ ] Start the Redis accessory (for Sidekiq):
  ```bash
  bundle exec kamal accessory boot redis
  ```

- [ ] Deploy the application:
  ```bash
  bundle exec kamal deploy
  ```

- [ ] Verify deployment:
  ```bash
  bundle exec kamal status
  ```

### 5. Additional Configuration
- [ ] Set up the Rails app for SSL:
  ```ruby
  # config/environments/production.rb
  config.force_ssl = true
  ```

- [ ] Configure cron jobs for regular tasks (if needed):
  ```bash
  bundle exec kamal exec --reuse web "whenever --update-crontab"
  ```

- [ ] Run database migrations on deploy:
  ```bash
  bundle exec kamal app exec --reuse web bin/rails db:migrate
  ```

### 6. Maintenance Commands
- [ ] Document common maintenance commands:
  ```
  # View logs
  bundle exec kamal app logs
  
  # Run console
  bundle exec kamal app exec --reuse web bin/rails console
  
  # Restart application
  bundle exec kamal app restart
  
  # Redeploy without rebuilding
  bundle exec kamal deploy --skip-build
  ```

## Acceptance Criteria
- [ ] Application is successfully deployed to production environment
- [ ] Zero-downtime deployments are working correctly
- [ ] SSL is properly configured with valid certificates
- [ ] Database migrations run automatically
- [ ] Automated deployments trigger on push to main branch
- [ ] Application is accessible at https://gothired.ai/

## Related Resources
- [[Kamal 2 Documentation](https://kamal-deploy.org/)](https://kamal-deploy.org/)
- [[Rails 8 Deployment Guide](https://rubyonrails.org/2024/11/7/rails-8-no-paas-required)](https://rubyonrails.org/2024/11/7/rails-8-no-paas-required)
- [[Hostinger VPS Documentation](https://www.hostinger.com/tutorials/vps)](https://www.hostinger.com/tutorials/vps)

---

**Labels**: devops, production, deployment, kamal, rails8
**Priority**: High
**Estimate**: 2-3 days

Citations:
[1] https://devcenter.upsun.com/posts/rails8-upsun-tutorial/
[2] https://www.beansmile.com/posts/deploying-rails-applications-with-kamal-2-guide
[3] https://rubyonrails.org/2024/11/7/rails-8-no-paas-required
[4] https://jetthoughts.com/blog/automate-your-deployments-with-kamal-2-github-actions-devops-development/
[5] https://thoughtbot.com/blog/ssl-for-rails-with-heroku-and-dnsimple
[6] https://render.com/docs/deploy-rails
[7] https://www.writesoftwarewell.com/docked-setup-rails-app-on-docker/
[8] https://rameerez.com/kamal-tutorial-how-to-deploy-a-postgresql-rails-app/
[9] https://www.margareti.com/posts/1
[10] https://dev.to/upsun/deploy-your-first-rails-8-application-from-zero-to-production-in-under-10-minutes-29b4
[11] https://www.reddit.com/r/rails/comments/lp1cur/could_i_deploy_my_rails_app_on_hostinger/
[12] https://www.reddit.com/r/rails/comments/182djm6/adding_ssl_to_a_ruby_on_rails_application/
[13] https://stackoverflow.com/questions/54383233/how-to-dockerize-a-rails-application-with-mysql-nginx-and-cron-tasks-using-dock
[14] https://dev.to/eduardinni/kamal-how-to-integrate-with-github-actions-with-multiple-destinations-3gmm
[15] https://www.pluralsight.com/resources/blog/guides/using-https-with-ruby-on-rails
[16] https://stackoverflow.com/questions/13444105/how-to-deploy-a-rails-app-to-a-vps-or-dedicated-server
[17] https://kamal-deploy.org/
[18] https://www.youtube.com/watch?v=lJ53r2QUX_M
[19] https://www.youtube.com/watch?v=ImqznBAzr_k
[20] https://www.reddit.com/r/rails/comments/1i7akkc/easiest_way_to_deploy_a_postgres_rails_8_app_to/
[21] https://sulmanweb.com/rails-8-modern-crud-development-guide
[22] https://github.com/basecamp/kamal
[23] https://blog.cloud66.com/running-rails-development-with-a-fake-domain-and-ssl
[24] https://docs.docker.com/guides/ruby/containerize/
[25] https://www.hostinger.com/vps/rails-hosting
[26] https://www.codewithjason.com/dockerize-rails-application/
[27] https://stackoverflow.com/questions/34201839/how-to-set-up-and-use-rails-environment-variables-in-production-server
[28] https://www.hostinger.com/tutorials/install-ruby-on-rails-on-ubuntu
[29] https://stackoverflow.com/questions/66815380/dns-records-set-up-correctly-server-ip-loads-but-domain-still-doesnt-work
[30] https://www.hostinger.com/tutorials/docker-start-a-container
[31] https://discuss.rubyonrails.org/t/preparing-rails-project-for-production-environment-and-a-question-about-content-tag/84311

---
Answer from Perplexity: https://www.perplexity.ai/search/please-improve-this-prompt-and-nGZ7lyIUT5WRE.LqQkHRiw?utm_source=copy_output
