### ISSUE TITLE
Add WordPress Blog to /blog Subdirectory on GotHired.ai

### ISSUE THREAD

**Issue by gabrielrubens** [gabrielrubens/gothired#8]
# GitHub Issue: Add WordPress Blog to /blog Subdirectory on GotHired.ai

## Overview
Implement a WordPress blog at `https://gothired.ai/blog` while maintaining our existing Rails 8 app as the main application. This will create a content marketing channel to drive organic traffic to GotHired.ai through SEO-optimized articles.

## Objectives
- Set up WordPress in a `/blog` subdirectory
- Configure proper routing between our Rails app and WordPress
- Ensure seamless user experience and consistent branding
- Optimize WordPress for SEO and performance
- Integrate with existing Kamal/Docker deployment setup

### 1. Server Preparation
- [ ] SSH into the Hostinger VPS:
  ```bash
  ssh deploy@your-server-ip
  ```
- [ ] Create a dedicated directory for WordPress:
  ```bash
  sudo mkdir -p /var/www/wordpress
  sudo chown -R deploy:deploy /var/www/wordpress
  ```
- [ ] Create a separate MySQL database for WordPress:
  ```bash
  # This can be done through Hostinger control panel or via command line
  # Example with command line:
  mysql -u root -p
  CREATE DATABASE wordpress_gothired;
  CREATE USER 'wordpress_user'@'localhost' IDENTIFIED BY 'secure_password';
  GRANT ALL PRIVILEGES ON wordpress_gothired.* TO 'wordpress_user'@'localhost';
  FLUSH PRIVILEGES;
  EXIT;
  ```

### 2. Docker Configuration for WordPress
- [ ] Create a `docker-compose.wordpress.yml` file in the project root:
  ```yaml
  version: '3'
  
  services:
    wordpress:
      image: wordpress:latest
      restart: always
      environment:
        WORDPRESS_DB_HOST: wordpress-db
        WORDPRESS_DB_USER: wordpress_user
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: wordpress_gothired
        WORDPRESS_CONFIG_EXTRA: |
          define('WP_SITEURL', 'https://gothired.ai/blog');
          define('WP_HOME', 'https://gothired.ai/blog');
          define('WP_CONTENT_URL', 'https://gothired.ai/blog/wp-content');
      volumes:
        - /var/www/wordpress:/var/www/html
      networks:
        - gothired_network
        - wordpress_network
    
    wordpress-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: wordpress_gothired
        MYSQL_USER: wordpress_user
        MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes:
        - wordpress-db-data:/var/lib/mysql
      networks:
        - wordpress_network
  
  networks:
    gothired_network:
      external: true
    wordpress_network:
      driver: bridge
  
  volumes:
    wordpress-db-data:
  ```

### 3. Nginx Configuration for Subdirectory Routing
- [ ] Create an Nginx configuration template for Kamal in your Rails project:
  ```
  # config/deploy/nginx.conf.erb
  server {
    listen 80;
    listen [::]:80;
    server_name ;
    
    location / {
      return 301 https://$host$request_uri;
    }
  }
  
  server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ;
    
    # SSL configuration (managed by Kamal)
    ssl_certificate /etc/letsencrypt/live//fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live//privkey.pem;
    
    # Additional SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    
    # Route /blog requests to WordPress
    location ^~ /blog {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://wordpress:80;
      proxy_redirect off;
    }
    
    # Main application (Rails)
    location / {
      proxy_pass http://web;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Host $host;
    }
  }
  ```

- [ ] Update the Kamal configuration to use this Nginx template:
  ```yaml
  # In config/deploy.yml
  proxy:
    # ... existing config ...
    nginx_template: config/deploy/nginx.conf.erb
  ```

### 4. WordPress Setup and Configuration
- [ ] Add WordPress deployment to your Kamal setup:
  ```bash
  # Update deploy.yml to include WordPress as an accessory
  ```
  
  Add this to your `deploy.yml` file:
  ```yaml
  accessories:
    # ... existing accessories ...
    wordpress:
      compose:
        file: docker-compose.wordpress.yml
        service: wordpress
      host: deploy@your-server-ip
      env:
        secret:
          - WORDPRESS_DB_PASSWORD
  ```

- [ ] Add the WordPress database password to Kamal secrets:
  ```bash
  echo "your-secure-wordpress-password" > .kamal/secrets/WORDPRESS_DB_PASSWORD
  ```

### 5. WordPress Theme and Content Preparation
- [ ] Create or select a WordPress theme matching the GotHired.ai branding
- [ ] Configure WordPress settings:
  - [ ] Set permalinks to `/blog/%postname%/` format
  - [ ] Install and configure essential WordPress plugins:
    - Yoast SEO for search optimization
    - WP Rocket or a similar caching plugin
    - Wordfence Security for WordPress security
    - Classic Editor or Gutenberg based on preference
    - Contact Form 7 or similar
    - UpdraftPlus for backups

### 6. Integration and Testing
- [ ] Deploy WordPress using Kamal:
  ```bash
  bundle exec kamal accessory boot wordpress
  ```

- [ ] Visit `https://gothired.ai/blog/wp-admin` to complete WordPress setup
- [ ] Test the subdirectory setup by:
  - Navigating between main app and blog
  - Verifying SSL works correctly on blog pages
  - Checking all internal links function properly

### 7. Header/Footer Integration
- [ ] Create header/footer in WordPress that visually match your Rails app
- [ ] Ensure navigation links between the blog and main app work correctly
- [ ] Add tracking codes (Google Analytics) to WordPress site

### 8. Deployment and Maintenance Process
- [ ] Document the WordPress update process:
  ```bash
  # Pull latest WordPress image
  bundle exec kamal accessory redeploy wordpress
  ```

- [ ] Set up automated backups for WordPress database and files
- [ ] Configure notification system for WordPress security issues

## Acceptance Criteria
- [ ] WordPress is successfully installed and accessible at `https://gothired.ai/blog`
- [ ] All WordPress pages load with correct styling and branding consistent with main app
- [ ] SSL is properly configured on all WordPress pages
- [ ] SEO optimization plugins and settings are properly configured
- [ ] Navigation between main app and blog is seamless
- [ ] WordPress backups are properly configured
- [ ] Documentation for maintenance procedures is complete

## Notes and Considerations
- This approach uses a separate Docker container for WordPress but integrates it via Nginx
- WordPress and Rails will have separate databases for better isolation
- The setup preserves the existing Rails deployment pipeline while adding WordPress
- Consider implementing a custom WordPress theme that matches the main application's design
- A Multi-container approach makes updates easier and keeps the apps isolated

---

**Labels**: wordpress, blog, content-marketing, seo
**Priority**: Medium
**Estimate**: 2-3 days
**Dependencies**: Requires successful completion of production environment setup

---
Answer from Perplexity: https://www.perplexity.ai/search/please-improve-this-prompt-and-nGZ7lyIUT5WRE.LqQkHRiw?utm_source=copy_output
